# Site Settings
lang: en
title: Chloe Page
# tagline: Bulma Clean Theme
# email: your-email@domain.com
description: >
  Personal and professional website of Chloe Page, Neuroscientist
baseurl: ""

permalink: pretty
favicon: /favicon.png
gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Chloe"
      layout: post
      image: 
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
